w4d5/MusicApp/config/routes.rb
Musicapp::Application.routes.draw do
  root to: redirect("/bands")

  resource :session, only: [:create, :destroy, :new]

  resource :user, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy]
end

w4d5/MusicApp/app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

w4d5/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

w4d5/MusicApp/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label>Name
    <input type="text" name="band[name]" value="<%= band.name %>">
    </label>
  </p>

  <input type="submit">
</form>

w4d5/MusicApp/app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render "form", band: @band %>

w4d5/MusicApp/app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
</ul>

<a href="<%= new_band_url %>" >New band</a>

w4d5/MusicApp/app/views/bands/new.html.erb
<h1>New Band!</h1>

<%= render "form", band: @band %>

w4d5/MusicApp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h4>Albums</h4>

<ul>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><%= album.name %></a></li>
  <% end %>
</ul>

<h4>Links</h4>
<ul>
  <li><a href="<%= new_band_album_url(@band) %>">New album</a></li>
  <li><a href="<%= edit_band_url(@band) %>">Edit Band</a></li>
  <li>
    <form action="<%= band_url(@band) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Band">
    </form>
  </li>
  <li><a href="<%= bands_url %>">All bands</a></li>
</ul>