w4d5/MusicApp/config/routes.rb
Musicapp::Application.routes.draw do
  root to: redirect("/bands")

  resource :session, only: [:create, :destroy, :new]

  resource :user, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy]
end

w4d5/MusicApp/app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :user
  belongs_to :track

  validates :content, :track_id, :user_id, presence: true
end

w4d5/MusicApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user!

  def create
    note = current_user.notes.new(note_params)
    note.save
    flash[:errors] = note.errors.full_messages

    redirect_to track_url(note.track_id)
  end

  def destroy
    note = current_user.notes.find(params[:id])
    note.destroy
    redirect_to track_url(note.track_id)
  end

  private
  def note_params
    params.require(:note).permit(:content, :track_id)
  end
end

w4d5/MusicApp/app/views/note/_form.html.erb
<h2>New Note</h2>

<form action="<%= notes_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>">

  <p>
    <label for="note_content">Content</label><br>
    <textarea id="note_content"
      rows="7" cols="30"
      name="note[content]"></textarea>
  </p>

  <input type="submit">
</form>

w4d5/MusicApp/app/views/note/_note.html.erb
<pre><%= note.content %></pre>
<p>Authored by: <%= note.user.email %></p>

<% if note.user_id == current_user_id %>
  <form action="<%= note_url(note) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
    <input type="submit" value="Destroy Note">
  </form>
<% end %>