w4d5/MusicApp/config/routes.rb
Musicapp::Application.routes.draw do
  root to: redirect("/bands")

  resource :session, only: [:create, :destroy, :new]

  resource :user, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy]
end

w4d5/MusicApp/app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band
  has_many :tracks, dependent: :destroy

  # can't use presence validation with boolean field
  validates :band, :name, :year, presence: true
  validates :live, inclusion: { in: [true, false] }
  validates :name, uniqueness: { scope: :band_id }
  validates :year, numericality: { minimum: 1900, maximum: 9000 }
end

w4d5/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :live, :name, :year)
  end
end

w4d5/MusicApp/app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>
<% button_text = album.persisted? ? "Update Album!" : "Create Album!" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label>Name
      <input type="text" name="album[name]" value="<%= album.name %>">
    </label>
  </p>

  <p>
  <label>Band
    <select name="album[band_id]">
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </label>
  </p>

  <p>
    <input
      type="radio"
      name="album[live]"
      value="t"
      id="album_live_t"
      <%= "checked" if album.live %>>
    <label for="album_live_t">Live</label>
    <input
      type="radio"
      name="album[live]"
      value="f"
      id="album_live_f"
      <%= "checked" if !album.live %>>
    <label for="album_live_f">Studio</label>
  </p>

  <p>
    <label>Year
      <input type="number" name="album[year]" value="<%= album.year %>">
    </label>
  </p>

  <input type="submit" value="<%= button_text %>">
</form>

w4d5/MusicApp/app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>

<%= render "form", album: @album %>

w4d5/MusicApp/app/views/albums/new.html.erb
<h1>New <%= @band.name %> Album!</h1>

<%= render "form", album: @album %>

w4d5/MusicApp/app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<ul>
  <% @album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><%= track.name %></a></li>
  <% end %>
</ul>

<h4>Links</h4>
<ul>
  <li><a href="<%= new_album_track_url(@album) %>">New track</a></li>
  <li><a href="<%= edit_album_url(@album) %>">Edit album</a></li>
  <li>
    <form action="<%= album_url(@album) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Album">
    </form>
  </li>
  <li><a href="<%= band_url(@album.band) %>"><%= @album.band.name %></a></li>
</ul>